POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": "150",
    "userId": "5f462d3c0a87ca185ad8de8e"
}