POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rpa2F5dHRhamEiLCJpYXQiOjE1OTg0NzAyNTJ9.TFZDe6R4xNQQhx-Tg86Vwuh6fVjieLBptE2_66aKjh8

{
    "title": "TESTINGBLOGI",
    "author": "testiukon kaveri",
    "url": "http://www.fi",
    "likes": "175000"
}